export const GOOGLE_API_KEY = 'AIzaSyCs8iHIiSD7O0f15VNk5mmerXBLO-0BKsY';
export const BOM_API_KEY = 'fbbb89795db54612ad9598e2ce77b709';

export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
export const DISPLAY_SUCCESS = 'DISPLAY_SUCCESS';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const SENDING_MESSAGE = 'SENDING_MESSAGE';
